// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaOVj6amNwQhmfCjs-kcuAvmSlPKnuhXA',
    appId: '1:723734396608:web:54a112268cac2a39f9f725',
    messagingSenderId: '723734396608',
    projectId: 'fitness-tracker-app-3c340',
    authDomain: 'fitness-tracker-app-3c340.firebaseapp.com',
    storageBucket: 'fitness-tracker-app-3c340.firebasestorage.app',
    measurementId: 'G-7JJPX7Q4KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyossm_86w897IYDFuEqZkBOx7QWp7j_U',
    appId: '1:723734396608:android:2822496eadcdc826f9f725',
    messagingSenderId: '723734396608',
    projectId: 'fitness-tracker-app-3c340',
    storageBucket: 'fitness-tracker-app-3c340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48OOVRbLFHnaGGKi3FifEuwK4RaHCjMA',
    appId: '1:723734396608:ios:494b3a6d17902d5df9f725',
    messagingSenderId: '723734396608',
    projectId: 'fitness-tracker-app-3c340',
    storageBucket: 'fitness-tracker-app-3c340.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );
}
